### PR TITLE
Some final form updates ;)

### PR DESCRIPTION
**Pull request by cameronbrill**

### CODE REVIEW

**Review by AdilRas — COMMENTED** [review]
Might want to change the "you" on line 114 of forms.py to the hackathon name or smth.

**Comment by cameronbrill** [comment]
> Might want to change the "you" on line 114 of forms.py to the hackathon name or smth.

good catch

**Comment by cameronbrill** [comment]
Problem: We started apps before migrating the new mandatory checkbox field
Solution: Make it nullable in the db

**Comment by cameronbrill** [comment]
Problem: address field was nullable (since it's optional), but would cause an error if incorrect address or no address
Solution: set blank=True for the address field (don't ask me why, but it works)

**Review by AdilRas — APPROVED** [review]
rick

**Pull request merged**
